# Generated by Django 4.2.4 on 2023-08-29 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="photo",
            new_name="image",
        ),
        migrations.RemoveField(
            model_name="question",
            name="option1",
        ),
        migrations.RemoveField(
            model_name="question",
            name="option2",
        ),
        migrations.RemoveField(
            model_name="question",
            name="option3",
        ),
        migrations.RemoveField(
            model_name="question",
            name="option4",
        ),
        migrations.RemoveField(
            model_name="question",
            name="question_text",
        ),
        migrations.RemoveField(
            model_name="result",
            name="result_text",
        ),
        migrations.AddField(
            model_name="question",
            name="statement",
            field=models.CharField(
                max_length=500, null=True, verbose_name="Question statement"
            ),
        ),
        migrations.AddField(
            model_name="result",
            name="answers",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="result",
            name="questions",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option1", models.CharField(max_length=200)),
                ("option2", models.CharField(max_length=200)),
                ("option3", models.CharField(max_length=200)),
                ("option4", models.CharField(max_length=200)),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=2,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, max_length=500, upload_to="photos/%Y/%m/%d/"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.question"
                    ),
                ),
            ],
        ),
    ]
