# Generated by Django 4.2.4 on 2023-08-29 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0002_rename_photo_question_image_remove_question_option1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="question_number",
        ),
    ]
